### ISSUE TITLE
Automatic graph reset?

### ISSUE THREAD

**Issue by richorama** [matiii/Dijkstra.NET#10]
Hi, thanks for writing the library, It's very useful.

I have just hit a problem where subsequent uses of the same same graph result in inconsistent results. 

And then I found `graph.Reset()`

I wonder if the `dijkstra.Process()` could call this automatically? It might save other developers some time.

Happy to create the PR.

**Comment by matiii** [comment]
That is true that dijksrta  mutate graph state. I think it's unwanted beahaviour. I will consider it during development of feature releases.

**Comment by matiii** [comment]
Since 1.0.9 version, Dijkstra any more mutate graph. Such problems shouldn't occur any more. #16
