### ISSUE TITLE
Convex polygonal obstacles

### ISSUE THREAD

**Issue by bulutkartal** [matiii/Dijkstra.NET#15]
Is there a way to use it with convex polygonal obstacles and coordinates?

**Comment by matiii** [comment]
Could you provide more information ? Code examples etc ?

**Comment by bulutkartal** [comment]
[Graphical](https://github.com/alvpickmans/Graphical) uses Dijkstra's algorithm to calculate shortest path with polygonal obstacles.

**Comment by matiii** [comment]
I have never use graphs for such purpose. I suspect the main challenge is to determine correct vertices and weights between corners of polygonal obstacles. If you have some idea how library could help with it PR welcome.

**Comment by matiii** [comment]
Any answer since 3 month. Issue closed.
