### ISSUE TITLE
The output is the index value, not the node value

### ISSUE THREAD

**Issue by Fay86** [matiii/Dijkstra.NET#31]
Use the function AddNode(1), but the last output node is the corresponding index, so the input becomes useless

**Comment by matiii** [comment]
Hi, I have plan to provide more simpler graph, without custom information saved in node.

**Comment by matiii** [comment]
Hi, I have plan to provide more simpler graph, without custom information saved in node.

**Comment by matiii** [comment]
Hi since 1.2.1 you can use simple Graph, without custom informations in node and edge. Check the last PR #42
