### ISSUE TITLE
Get custom info

### ISSUE THREAD

**Issue by ridicoulous** [matiii/Dijkstra.NET#36]
Hello. Thank you a lot for wonderful library!  (Where the "tips" section? =))
I not found solution how I can get custom info pushed to graph here:

`
graph.Connect(1, 2, 5, "some custom information in edge"); //First node has key equal 1
ShortestPathResult result = graph.Dijkstra(1, 2); //result contains the shortest path
var path = result.GetPath();
`
So: I would like to have opportunity to get "some custom information in edge" by nodes links or whatever

**Comment by matiii** [comment]
Hi, good question. In ver 1.2.1 node will return enumerable of edges. Is it ok for you ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
