### ISSUE TITLE
ShortestPath extension for getting custom info for path

### ISSUE THREAD

**Issue by ridicoulous** [matiii/Dijkstra.NET#38]
I'll try to provide a solution to getting a data chain of custom info to detalize connections

**Comment by matiii** [comment]
Hi, very good idea. I think its better if TheShortestPathResult will have this functionality than extension method. I gave you some suggestion about multiple edges between nodes, we have to take account of it.To achive it we have to extend dijkstra algorithm.

**Comment by Vannevelj** [comment]
👍 I'd be interested in this as well. In my situation there's only a single edge between nodes so the proposed PR works for me. I'm not sure how you would solve the comment in the PR though -- maybe just return a collection of all edges on the node if there are multiple?

**Comment by ridicoulous** [comment]
@Vannevelj In my case I used pre prepared data grouped by nodes connections and it also worked fine for me. Sure, the simplest way is to return whole edges collection, but it could  be hard to work with it

**Comment by Vannevelj** [comment]
It sounds like right now we are all rolling with our own lookup logic. If someone has a scenario with multiple edges then they'll still be able to do it in a custom way themselves, I suppose?

**Comment by matiii** [comment]
Since v 1.2.1 you can get whole collection of edges or just first edge. Check #42
