### ISSUE TITLE
Ability to add data to a connection

### ISSUE THREAD

**Issue by isaacabraham** [matiii/Dijkstra.NET#41]
It would be useful to attach metadata to arbitrary connections in the graph (and retrieve them when getting a path back).

**Comment by isaacabraham** [comment]
Ok - I can see that the `custom` arg is meant for this now. But how do we get the custom data back out again?

**Comment by isaacabraham** [comment]
OK - further investigation shows that the current repo has methods like this:

https://github.com/matiii/Dijkstra.NET/blob/master/src/Dijkstra.NET/Graph/Node.cs#L59-L62

However they aren't present in v1.2 of the nuget package:

![image](https://user-images.githubusercontent.com/1781813/52905167-99b66100-3236-11e9-8edb-ff38708b1622.png)

Have I missed something here?

**Comment by matiii** [comment]
Hi, yes since 1.2.1 version you have such feature or you can enumerate node to get all contained edges. Check #42. Is it ok for you ?

**Comment by matiii** [comment]
Any response for few months, I close issue.
