### ISSUE TITLE
AddNode method

### ISSUE THREAD

**Issue by elevir** [matiii/Dijkstra.NET#44]
Hello!
Nodes in a graph have indices starting from 1, but it is inconvenient.
I suggest to make following changes in method `AddNode`, If it is possible:
```
public uint AddNode(T item)
{
   uint key = (uint) _nodes.Count;
   AddNode(key, item);
   return key;
}
```
Or is there any reason that 1 is added to key?

Thanks!

**Comment by mitchellri** [comment]
Having 0 as an invalid index has been helpful for me.
When you're manually searching for a node that meets a condition, and if no nodes meet that condition, you know it will be invalid because the uint you're assigning the result to will be 0.

**Comment by elevir** [comment]
@mitchellri we can always use -1 for invalid values (or in this case max value of uint), this value is used rarely unlike zero. Moreover, it is standard practice to use -1 as invalid value.

**Comment by mitchellri** [comment]
@elevir The keys are `uint` and -1 is not a valid `uint`. Using `uint.MaxValue` opens up easier vulnerability to accidental overflows.

**Comment by elevir** [comment]
@mitchellri ok, you're right. But anyway zero is frequently used value, and I still think that using zero as invalid value is very inconvenient and new framework users can be confused by this behavior. Well, when I found this library, I was confused and had to look at source code to make sure that indices start from 1 :)

**Comment by matiii** [comment]
Moreover all database systems start set keys from 1. As @mitchellri  said 0 means that node does not belong to graph.
