### ISSUE TITLE
Not compatible with Xamarin

### ISSUE THREAD

**Issue by gustaveracosta** [matiii/Dijkstra.NET#9]
Could not install package 'Dijkstra.NET 1.0.6'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by matiii** [comment]
Please check v1.0.7

**Comment by matiii** [comment]
No response since 14.10, I assume it is working.
